/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Darwin TrapBook-Air.local 16.0.0 x86_64"
#define LGL_COMPILED "Thu Feb  2 15:50:34 EST 2017"
#define LGL_RELEASED "Thu Jul  7 10:21:35 CEST 2016"
#define LGL_VERSION "bbc"
#define LGL_ID "923038088b727dcc8bd03aa8dfb5013bd03bf8c4"
